[tool.poetry]
name = "bioinfo"
version = "0.1.0"
description = ""
authors = ["valkheim"]

[tool.poetry.dependencies]
python = "^3.7"
matplotlib = "^3.3.3"
pytest = "^6.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
